/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#858480",
        "outline-variant": "#c6c6cd",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        tertiary: "#000000",
        "surface-container-high": "#dce9ff",
        surface: "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#fed488",
        "on-background": "#0b1c30",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        "primary-fixed": "#dae2fd",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#785a1a",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        background: "#f8f9ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#5d4201",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed": "#1c1c19",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#261900",
        "inverse-primary": "#bec6e0",
        "secondary-fixed": "#ffdea5",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        primary: "#000000",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#c8c6c2",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#1c1c19",
        "secondary-fixed-dim": "#e9c176",
        "tertiary-fixed": "#e5e2dd",
        outline: "#76777d",
        secondary: "#775a19",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#474743",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "4px",
        gutter: "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "display-lg": ["Noto Serif", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md-mobile": ["Noto Serif", "serif"],
        "headline-sm": ["Noto Serif", "serif"],
        "headline-md": ["Noto Serif", "serif"],
        headline: ["Noto Serif", "serif"],
        display: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
